### ISSUE TITLE
Git 2.12.0 does not support long paths (regression)

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1428]
Reproduce build: https://ci.appveyor.com/project/FeodorFitsner/git-long-paths/build/1.0.4

Related Git issue: https://github.com/git-for-windows/git/issues/1095

Solution: Install Git 2.12.1

Temp workaround - installing Git 2.12.1 during the build:

```yaml
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-git-2.12.1.ps1'))
```

Green build with workaround applied: https://ci.appveyor.com/project/FeodorFitsner/git-long-paths/build/1.0.12

**Comment by asottile** [comment]
Hitting this here:
- https://ci.appveyor.com/project/asottile/pre-commit-hooks/build/job/1vwlw26ni3nkpjmn
- https://github.com/pre-commit/pre-commit-hooks/pull/188

**Comment by FeodorFitsner** [comment]
We are going to install Git 2.12.1 fixing the issue with long paths: https://github.com/git-for-windows/git/issues/1095#issuecomment-288209612

**Comment by asottile** [comment]
It seems that even with 2.12.1 there's this additional (related) issue: https://github.com/git-for-windows/git/issues/1106

**Comment by FeodorFitsner** [comment]
If `git diff` affects your build you can switch back to 2.11.0 during the build: https://github.com/appveyor/ci/issues/1428#issue-215639767

**Comment by asottile** [comment]
This seems not yet fixed: https://ci.appveyor.com/project/asottile/pre-commit/build/job/2w93igc7u1lsrdxd

**Comment by FeodorFitsner** [comment]
@asottile How is that error related to git long paths issue? Could you please collaborate?

**Comment by asottile** [comment]
See https://github.com/git-for-windows/git/issues/1106 (Linked above in https://github.com/appveyor/ci/issues/1428#issuecomment-289317615)

**Comment by FeodorFitsner** [comment]
Ah, it's `git diff` issue. I've closed this one because it was related to long paths.

Have you tried installing Git 2.12.2 during the build? Was `git diff` issue fixed in 2.12.2?

**Comment by asottile** [comment]
The `git diff` issue is also related to long paths (why I commented here :D)

I'm trying this patch,

```diff
$ git show
commit d569dbce83e32489cb9feb6aad9e9170eb3655b9
Author: Anthony Sottile <asottile@umich.edu>
Date:   Tue Mar 28 13:28:28 2017 -0700

    Try 2.12.2 in appveyor

diff --git a/appveyor.yml b/appveyor.yml
index 013e142..9bb2d43 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -5,7 +5,8 @@ environment:
     matrix:
         - TOXENV: py27
         - TOXENV: py36
-
+init:
+- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-git-2.12.2.ps1'))
 install:
     - "SET PATH=C:\\Python36;C:\\Python36\\Scripts;%PATH%"
     - pip install tox virtualenv --upgrade
```

https://ci.appveyor.com/project/asottile/pre-commit/build/job/o5vfy5pli2ncu0pg

Trying 2.21.1:

```diff
$ git show
commit 579109b5ad903860da3928b089f73b894ec40c0a
Author: Anthony Sottile <asottile@umich.edu>
Date:   Tue Mar 28 13:31:26 2017 -0700

    Try 2.12.1?

diff --git a/appveyor.yml b/appveyor.yml
index 9bb2d43..7260776 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -6,7 +6,7 @@ environment:
         - TOXENV: py27
         - TOXENV: py36
 init:
-- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-git-2.12.2.ps1'))
+- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-git-2.12.1.ps1'))
 install:
     - "SET PATH=C:\\Python36;C:\\Python36\\Scripts;%PATH%"
     - pip install tox virtualenv --upgrade
```

Still fails: https://ci.appveyor.com/project/asottile/pre-commit/build/job/b5mixcxa1rqb75c5

**Comment by asottile** [comment]
Yes still failing with 2.12.2: https://ci.appveyor.com/project/asottile/pre-commit/build/job/nbdhks1ip79fiykq

(Via your comment on this ticket: https://github.com/git-for-windows/git/issues/1106#issuecomment-289902947)

**Comment by FeodorFitsner** [comment]
OK, try enabling long paths then by:

```
init:
- git config --global --add core.longpaths true
```

**Comment by asottile** [comment]
Still failing: 

https://ci.appveyor.com/project/asottile/pre-commit/build/job/igw9a55t6vtcc1wu

**Comment by asottile** [comment]
An additional failure mode: https://ci.appveyor.com/project/asottile/aspy/build/1.0.17/job/diath3ouqva9ouej

**Comment by FeodorFitsner** [comment]
OK, I've got a faster workaround script to get back to 2.11.1 during the build:

```
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-git-2.11.1-v3.ps1'))
```

aspy.yaml build works with it: https://ci.appveyor.com/project/FeodorFitsner/aspy-yaml

Watch that issue in Git repo to get notified when it's fixed.
