### ISSUE TITLE
Unable to load multiple test assemblies with the same name from different folders

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1746]
Seems like reflection issue (API restriction: The assembly `<path>` has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.)

[Discussion](http://help.appveyor.com/discussions/problems/2211-multiple-test-assemblies-only-one-gets-executed)

**Comment by igitur** [comment]
I can understand that reflection and duplicate assembly names causes an issue during auto-discovery, but I don't understand why it would be a problem with auto-discovery switched off. I deliberately list my assemblies to test, so surely the test runner should just iterate through them?

**Comment by IlyaFinkelshteyn** [comment]
@igitur Right, but we still need to check dll with reflection to ensure that it is managed and that it is test assembly, and also to find correct test runner. Problem that the same object is being used to call reflection for each of them, but it should be disposed every time to avoid this situation. So this is matter of `using` statement scope. Fixing now.

**Comment by igitur** [comment]
I hate to be that guy who posts this, because I hate it when people ask on my projects, but how is this issue progressing?

**Comment by IlyaFinkelshteyn** [comment]
It is actually checked in, will be in the next build worker image update. We will close this as it is done. Or if you see another update [here](https://www.appveyor.com/updates/), this means it is in prod. Should be in about a week.

**Comment by IlyaFinkelshteyn** [comment]
Fix is deployed, sorry it took that long.

**Comment by igitur** [comment]
I think something is still wrong. 

Have a look at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.669

The tests for the build `net461` complete, as always.

What's new is that it now look for the `netcoreapp2.0` build. That's good news, but it looks for the assembly in the wrong path. It's expecting the assembly to be in `C:\projects\closedxml\ClosedXML_Tests\bin\Release\netcoreapp2.0\ClosedXML_Tests.dll` instead of `C:\projects\closedxml\ClosedXML_Tests\bin\Release\netcoreapp2.0\ClosedXML_Tests.dll`.

Or did I misunderstand something?

**Comment by IlyaFinkelshteyn** [comment]
I forked your repo and made it work by commenting out `platform: Any CPU` in YAML part. I did not debug this deeply, but here is my understanding of what happened:
- this fix did not work for you. Though we now allow assemblies with the same name, we restrict them to only "classic" .NET assemblies, e.g. assemblies which refer `mscorlib`. netstandard ones are not that kind so they are skipped. It is done to clearly differentiate "classic" .NET assemblies, which we find with **reflection**, and .NET core/standard ones, which we find with **analyzing** `.csproj` files.

- your `ClosedXML_Tests.csproj` was recognized as .NET Core/standard test project and was passed to `dotnet test` (not classic test runner like `nunit3-console`). I am not sure I fully understand how `dotnet test` interacts with `platform`, but as you see commenting it out fixed it.

But I am still not sure results are good. If you look at [my build](https://ci.appveyor.com/project/IlyaFinkelshteyn/closedxml/build/0.8.3), it seems that test results from `dotnet test` execution are logged but results from `nunit3-console` are not logged. Can you please look at this as your are more familiar with this test? Tell me what is still not right and we will see how to make it work.

**Comment by igitur** [comment]
@IlyaFinkelshteyn This time my apologies. I dropped the ball a bit on this one. I've looked at your comments and I have this feedback:

- commenting out `platform: Any CPU` solves the issue with discovery of the test assembly paths, but I still find it weird that including it is a problem. At least there's a workaround now.

- referring to your last paragraph about `dotnet test` vs `nunit3-console`: I first have to add that I'm getting some test assemblies being 'tested' twice, once with `dotnet test` and once with `nunit3-console`, e.g. the `net461` build of https://ci.appveyor.com/project/Pyropace/closedxml/build/0.92.827 . I don't think this is necessary and I think the `dotnet test` version should get preference. One could possibly check for references to 'NUnit` and `NUnit3TestAdapter`. If both references exist, the `dotnet test` should be sufficient. If only `NUnit` exists, the `nunit3-console` should be used. This is only a suggestion, and I don't have too much experience with running tests from different test runners.
- about the logging, even though multiple assemblies are being tested, I see only one set of tests' output, and I don't know which one. I would suggest that the test output be grouped per assembly in some way, which will require a UI change.
