### ISSUE TITLE
appveyor_repo_tag: true not honored ?

### ISSUE THREAD

**Issue by mh-cbon** [appveyor/ci#1754]
in this non tag commit build 
https://ci.appveyor.com/project/mh-cbon/go-msi/build/1.0.205

the system did run the deployment script,

```
Discovering tests...OK
Collecting artifacts...
Found artifact 'go-msi-386.msi' matching '*-386.msi' path
Found artifact 'go-msi-amd64.msi' matching '*-amd64.msi' path
Uploading artifacts...
[1/2] go-msi-386.msi (3,141,632 bytes)...100%
[2/2] go-msi-amd64.msi (3,313,664 bytes)...100%
never-fail jfrog bt pc --user %GH_USER% --key %BT_KEY% --licenses=MIT --vcs-url=https://github.com/%APPVEYOR_REPO_NAME% %GH_USER%/msi/%GH_APP%
```

even though the provider has the key `appveyor_repo_tag: true`
- https://github.com/mh-cbon/go-msi/blob/aac03a65d378875588c401a8f1c56fd2c7dc56c1/appveyor.yml#L95

___________

**BTW**
In this page
https://ci.appveyor.com/project/mh-cbon/go-msi/build/1.0.205
the link to the github repository version is wrong,
have https://github.com/mh-cbon/go-msi/commit/aac03a65d378875588c401a8f1c56fd2c7dc56c1
want https://github.com/mh-cbon/go-msi/tree/aac03a65d378875588c401a8f1c56fd2c7dc56c1

**Comment by mh-cbon** [comment]
my bad.

> However, please note that branch and appveyor_repo_tag are mutually exclusive. This is because, in the case of tag, it replaces the branch in the webhook content and there is no practical reliable way to recognize from what branch the tag was created. Therefore with this setting deployment will happen only for the master branch:

**Comment by mh-cbon** [comment]
https://ci.appveyor.com/project/mh-cbon/go-msi/build/1.0.207

https://github.com/mh-cbon/go-msi/blob/f9e1db7b5fd8af133850f5a427fb4725750f8bee/appveyor.yml#L90

```
cd && dir *msi
C:\gopath\src\github.com\mh-cbon\go-msi
 Volume in drive C has no label.
 Volume Serial Number is 1CB8-D4AA
 Directory of C:\gopath\src\github.com\mh-cbon\go-msi
08/29/2017  07:27 AM         3,141,632 go-msi-386-1.0.2.msi
08/29/2017  07:27 AM         3,141,632 go-msi-386.msi
08/29/2017  07:27 AM         3,313,664 go-msi-amd64-1.0.2.msi
08/29/2017  07:27 AM         3,313,664 go-msi-amd64.msi
               4 File(s)     12,910,592 bytes
               0 Dir(s)  29,190,443,008 bytes free
Discovering tests...OK
Collecting artifacts...
Found artifact 'go-msi-386.msi' matching '*-386.msi' path
Found artifact 'go-msi-amd64.msi' matching '*-amd64.msi' path
Uploading artifacts...
[1/2] go-msi-386.msi (3,141,632 bytes)...100%
[2/2] go-msi-amd64.msi (3,313,664 bytes)...100%
never-fail jfrog bt pc --user %GH_USER% --key %BT_KEY% --licenses=MIT --vcs-url=https://github.com/%APPVEYOR_REPO_NAME% %GH_USER%/msi/%GH_APP%
```

**Comment by mortenab** [comment]
I also experienced this issue on August 29th. The problem has gone away, so I guess it has been fixed?

**Comment by IlyaFinkelshteyn** [comment]
@mortenab no, we did not fix anything in this area. If you provide your YAML configuration and link to the specific build we could try to explain what happened.

**Comment by mortenab** [comment]
@IlyaFinkelshteyn I have discovered that it has happened at least twice, but it does not happen consistently. This is one of the builds https://ci.appveyor.com/project/Configit/configit-cli/build/0.0.148

This was a regular merge commit into our master branch and not a tag.

Due to company policy, I am not allowed to share the entire YAML config here, but here is the part that was not supposed to be executed:

```yaml
  deploy_script:
    - ps: npm publish
      on:
        appveyor_repo_tag: true        # deploy only on tag push
        is_release_tag: true           # deploy only if tag matches release     
```
The `is_release_tag` variable is set in the `init` phase based on a regular expression on the `APPVEYOR_REPO_TAG_NAME` environment variable. 

It seems both `appveyor_repo_tag` and the `APPVEYOR_REPO_TAG_NAME` is set during our non-tag build.

**Comment by mortenab** [comment]
It just happened again and it seems the `deploy_script` is always triggered when merging a pull request on GitHub.

**Comment by IlyaFinkelshteyn** [comment]
Ah I see the confusion now. Deployment conditions in this notation are valid for deployment **providers** (like built-in FTP or WebDeploy), but not deployment **script**. For script you can simple run something like this:

```
  deploy_script:
    - ps: if ($env:appveyor_repo_tag -and $env:is_release_tag) {npm publish}
```

**Comment by mortenab** [comment]
@IlyaFinkelshteyn thanks for the clarification. I will update our configuration. One final question: does AppVeyor itself skip the `deploy_script` target when building pull requests? That seems to be the case in our setup.

**Comment by IlyaFinkelshteyn** [comment]
There is UI-only (for security reasons) settings named `Enable deployments in Pull Requests` on the General tab for private projects.
