### ISSUE TITLE
NullReferenceException in .csproj analyzer

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1886]

**Comment by IlyaFinkelshteyn** [comment]
Temporary workaround is to use "Previous" image. In the most cases it is `Previous Visual Studio 2017` image.

**Comment by IlyaFinkelshteyn** [comment]
Should be fixed now. Please try to revert to the current image and reopen this issue if something wrong.

**Comment by tynorton** [comment]
We were using `Previous Visual Studio 2017`, and overnight it seems to have started failing again.

```
...
Patching .NET Core .csproj files
Object reference not set to an instance of an object.
```

We tried using the `Visual Studio 2017` image, but has the same failure. This is not fixed for us and we no longer have a working `Previous Visual Studio 2017`.

Please advise.

**Comment by IlyaFinkelshteyn** [comment]
@tynorton can you please do the following: 
- add `appveyor version` at `init` or `install` step
- try both images
- send us links to both builds.

**Comment by IlyaFinkelshteyn** [comment]
@tynorton also please add `echo %appveyor_build_worker_image%` after `appveyor version`

**Comment by IlyaFinkelshteyn** [comment]
@tynorton another fix is deployed, for your case. Sorry for the trouble.

**Comment by bkoelman** [comment]
I am still getting errors with latest VS2017 image. 

```
C:\projects\testablefilesystem\src\Analyzer.Vsix\bin\Release\TestableFileSystem.Analyzer.Vsix.vsix
obj\Release\netstandard1.3\TestableFileSystem.Interfaces.AssemblyInfo.cs(18,59): error CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision [C:\projects\testablefilesystem\src\Interfaces\TestableFileSystem.Interfaces.csproj]
obj\Release\netstandard1.3\TestableFileSystem.Interfaces.AssemblyInfo.cs(22,55): error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]] [C:\projects\testablefilesystem\src\Interfaces\TestableFileSystem.Interfaces.csproj]
obj\Release\net45\TestableFileSystem.Interfaces.AssemblyInfo.cs(18,59): error CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision [C:\projects\testablefilesystem\src\Interfaces\TestableFileSystem.Interfaces.csproj]
obj\Release\net45\TestableFileSystem.Interfaces.AssemblyInfo.cs(22,55): error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]] [C:\projects\testablefilesystem\src\Interfaces\TestableFileSystem.Interfaces.csproj]
Command exited with code 1
```

See https://ci.appveyor.com/project/bkoelman/testablefilesystem/build/0.1.0-pre-138-master.

**Comment by IlyaFinkelshteyn** [comment]
@bkoelman  Your error is different and very probably unrelated to the problem discussed in this issue. I am not sure I have full understanding because your build configuration change happens in UI and not in YAML, but my theory is that you added AssemblyInfo patching and did in in a way msbuild does not like. Error CS7035 looks pretty self-descriptive. If you need help in understanding what exactly wrong with your AssemblyInfo patching, please press `Export YAML` and send us the result.

**Comment by bkoelman** [comment]
Thanks for looking into this. Perhaps in the past, assembly-patching for
.VSIX projects in Core mode was skipped. I recall seeing a warning about
that. Some time ago I added the custom patching from another project. I'll
take a look later and let you know.

2017-12-05 11:24 GMT+01:00 Ilya Finkelshteyn <notifications@github.com>:

**Comment by bkoelman** [comment]
I did some more investigation. Turns out that [this project](https://github.com/bkoelman/CSharpGuidelinesAnalyzer/) uses the same mechanism, but builds fine. 

This is how it works: The vsix version is defined in .vsixmanifest using a placeholder:

```xml
    <Identity Id="CSharpGuidelinesAnalyzer..1d571424-b954-4fb3-8e9f-c8bcca9a17f0" Version="|%CurrentProject%;GetVsixPackageVersion|" Language="en-US" Publisher="Bart Koelman" />
```

Which depends on `GetVsixPackageVersion` target in the project file:

```xml
  <Target Name="GetVsixPackageVersion" Outputs="$(VsixPackageVersion)">
    <GetAssemblyIdentity AssemblyFiles="$(ProjectDir)$(OutDir)CSharpGuidelinesAnalyzer.dll">
      <Output TaskParameter="Assemblies" ItemName="assemblyVersionInfo" />
    </GetAssemblyIdentity>
    <PropertyGroup>
      <Pattern>(\d+)\.(\d+).(\d+)</Pattern>
      <In>%(assemblyVersionInfo.Version)</In>
      <VsixPackageVersion>$([System.Text.RegularExpressions.Regex]::Match($(In), $(Pattern)))</VsixPackageVersion>
    </PropertyGroup>
  </Target>
```

The target takes the output DLL and reads the assembly version (not file version) using a regular expression.

I did a compare between .vsixmanifest, .csproj and yaml files for both projects, but found nothing to explain the different behavior.

yaml for https://github.com/bkoelman/TestableFileSystem/:
```yaml
version: 0.1.0-pre-{build}-{branch}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: msbuild /t:restore src\TestableFileSystem.sln
build:
  project: src\TestableFileSystem.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - TestableFileSystem.Fakes.Tests.dll
after_test:
- cmd: >-
    set configuration=Release

    set opencover="%USERPROFILE%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"

    set testrunner="%xunit20%\xunit.console.x86.exe"

    set targets=".\src\Fakes.Tests\bin\%configuration%\net452\TestableFileSystem.Fakes.Tests.dll .\src\Analyzer.Tests\bin\%configuration%\net452\TestableFileSystem.Analyzer.Tests.dll -noshadow -appveyor"

    set filter="+[TestableFileSystem*]*  -[TestableFileSystem.*.Tests*]*  -[TestableFileSystem.Wrappers*]*"

    set coveragefile=".\CodeCoverage.xml"


    %opencover% -returntargetcode -register:user -target:%testrunner% -targetargs:%targets% -filter:%filter% -hideskipped:All -output:%coveragefile%

    SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%

    pip install codecov

    codecov -f %coveragefile%
artifacts:
- path: '**\TestableFileSystem*.nupkg'
```

yaml for https://github.com/bkoelman/CSharpGuidelinesAnalyzer/:
```yaml
version: 2.6.1-pre-{build}-{branch}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: msbuild /t:restore src\CSharpGuidelinesAnalyzer.sln
build:
  project: src\CSharpGuidelinesAnalyzer.sln
  verbosity: minimal
after_test:
- cmd: >-
    set configuration=Release

    set opencover="%USERPROFILE%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"

    set testrunner="%xunit20%\xunit.console.x86.exe"

    set target=".\src\CSharpGuidelinesAnalyzer\CSharpGuidelinesAnalyzer.Test\bin\%configuration%\net46\CSharpGuidelinesAnalyzer.Test.dll -noshadow -appveyor"

    set filter="+[CSharpGuidelinesAnalyzer*]*  -[CSharpGuidelinesAnalyzer.Test*]*"

    set coveragefile=".\CodeCoverage.xml"


    %opencover% -returntargetcode -register:user -target:%testrunner% -targetargs:%target% -filter:%filter% -hideskipped:All -output:%coveragefile%

    SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%

    pip install codecov

    codecov -f %coveragefile%
artifacts:
- path: '**\CSharpGuidelinesAnalyzer*.nupkg'
```

Can you please take another look? Both projects build without errors locally in Debug and Release mode.

**Comment by bkoelman** [comment]
@IlyaFinkelshteyn I did some more digging into my failing build and created https://github.com/appveyor/ci/issues/1972.
