### ISSUE TITLE
[VS 2017] MSVC 19.15.26726.0 fails to correclty compile constexpr

### ISSUE THREAD

**Issue by JohanMabille** [appveyor/ci#2598]
MSVC 19.14.26433.0 has been recently updated to MSVC 19.15.26726.0; this leads to compilation error due to bad constexpr handling, as can be seen in this [log](https://ci.appveyor.com/project/QuantStack/xtensor/build/1.0.3203/job/tqk4oh0dloj3tmu4).

The compilation was fine with the last MSVC (see [here](https://ci.appveyor.com/project/QuantStack/xtensor/build/1.0.3194/job/7f92b18bhqlvfhpr?fullLog=true)).

**Comment by FeodorFitsner** [comment]
VS 2017 has been updated to 15.8.1

**Comment by JohanMabille** [comment]
I hope so, however the [release notes](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.8.2) does not mention anything about that, and the [15.8.1 release notes](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.8.1) only mentions a change that is totally unrelated to this problem. "Previous Visual Studio 2017" as a workaround for now.

**Comment by JohanMabille** [comment]
So it seems that the 15.8 branch has some problems with constexpr handling ([issue1](https://developercommunity.visualstudio.com/content/problem/315586/internal-compiler-error-for-158-with-constexpr-sta.html), [issue2](https://developercommunity.visualstudio.com/content/problem/313146/an-internal-compiler-error-occured-c-vs-1580.html)) that will be fixed in 15.8.3 only (if not later for some of the issues).

Is there any mean on your side to test the build of one of these repos with the next version that will be deployed?
[xtensor](https://github.com/QuantStack/xtensor)
[mpark/variant](https://github.com/mpark/variant)

They make a heavy use of constexpr and if the builds fail, there is a chance that the next update will still break the build of many other projects.

**Comment by IlyaFinkelshteyn** [comment]
@JohanMabille as you see, this issue is assigned to `next-images-update` milestone. This means that this should be fixed before **major** (when we replace **previous**) image update.

We test our images with build repos we constantly add to https://github.com/appveyor-tests/. Can you create a more hello-world-style repo with `appveyor.yml` which will fail fast if this problem re-occurs so we can add it to our test repos too?

**Comment by FeodorFitsner** [comment]
It must be fixed in 15.8.4: https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.8.4

Related issue: https://github.com/appveyor/ci/issues/2614

**Comment by JohanMabille** [comment]
Awesome, thanks for this update! I hope it will fix most of our issues.

@IlyaFinkelshteyn I didn't forget you, I was really busy these last weeks; I should have more time now to start producing minimal test cases for the issues we experience with VS2017.

**Comment by JohanMabille** [comment]
The bug is still present in 15.8.4, the VS team confirmed they have a fix in 16.0.
By the way, we just created a [repo ](https://github.com/QuantStack/xcrash) with minimal examples to reproduces C++ compiler bugs, we hope it will help tracking and fixing these issues.

**Comment by FeodorFitsner** [comment]
Oh, damn. Let's re-open this issue then.

Is there a corresponding issue on VS website we can watch for?

**Comment by JohanMabille** [comment]
Yes, this [issue](https://developercommunity.visualstudio.com/content/problem/275141/c2131-expression-did-not-evaluate-to-a-constant-fo.html) is really similar to the one we have.

**Comment by JohanMabille** [comment]
It seems that VS2017 has been updated to 15.8.9, and Previous VS2017 is now 15.8.5 so both images are now broken. Is there a way to stick with VS2017 15.7.5 in appveyor? Otherwise we have no choice but removing VS2017 from our CI.

**Comment by JohanMabille** [comment]
Last update fixed the problem, we have enabled the tests on VS2017 again.
