### ISSUE TITLE
[VS2019] Strawberry perl's c++.exe is default compiler since last update

### ISSUE THREAD

**Issue by Farwaykorse** [appveyor/ci#3387]
When using CMake without specifying a compiler `c++.exe` in the strawberry Perl directory is used.

After running `vcvarsall.bat` CMake used to default to the msvc compiler in Visual Studio.
Now it tries to use GCC 8.3 in the Strawberry Perl directory.

[First failing job, < 30 min. after last succeeding run (line 150)](https://ci.appveyor.com/project/Farwaykorse/fwksudoku/builds/32293904/job/vkt3i0yvtyvhrc9l#L150)
````
-- CMake version: 3.17.1
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: C:/Strawberry/c/bin/c++.exe
-- Check for working CXX compiler: C:/Strawberry/c/bin/c++.exe - broken
````

This happens only on the VS2019 image, the VS2017 image works as expected.

Since the latest image update for Visual Studio 2019. [link](https://www.appveyor.com/updates/2020/04/19/)

----
Related:
Addition of Strawberry Perl: #3377

----
Edit:
Occurs when using the Ninja generator. (`cmake -G Ninja`)
No issue with CMake's MSBuild generator. (default on Windows)

----
A workaround I found is to set the environment variable CXX to `cl.exe`.

**Comment by FeodorFitsner** [comment]
Thanks for reporting that! We are working on the fix.

**Comment by FeodorFitsner** [comment]
The fix has been implemented. It should be working again. I'm leaving this issue opened to do a permanent fix into build images.

The fix (for internal notes):

```yaml
- ps: |
    if (Test-Path 'C:\Strawberry') {
      Remove-Path 'C:\Strawberry\c\bin'
      Remove-Path 'C:\Strawberry\perl\site\bin'
      $env:path = $env:path.replace('C:\Strawberry\c\bin;', '').replace('C:\Strawberry\perl\site\bin;', '')
    }
```

**Comment by andrew-aladev** [comment]
Hello, this issue still persists, but now `gmake` from `strawberryperl` is the first in the path before cygwin `make`. Should we create a new bug?

**Comment by martingalvan-nordic** [comment]
This is still happening on VS 16.11.7.
