### ISSUE TITLE
Error calling octo tool: No such file or directory on Ubuntu2004

### ISSUE THREAD

**Issue by olsh** [appveyor/ci#3828]
I get error when I'm trying to use Octopus deploy provider on Ubuntu2004 image
```
Error calling octo tool: No such file or directory
```

Here is the appveyor.yml
https://github.com/olsh/curl-to-csharp/blob/9ae4cafe66c0ccf41459379252819a099b1efdad/appveyor.yml

Here is the build log
https://ci.appveyor.com/project/olsh/curl-to-csharp/builds/44024789

What do I do wrong?

**Comment by FeodorFitsner** [comment]
Looking into that. Sorry for the delay!

**Comment by FeodorFitsner** [comment]
It should be fixed now - could you give it another try please?

**Comment by olsh** [comment]
I still get the same error
Here is the build https://ci.appveyor.com/project/olsh/curl-to-csharp/builds/44121053

**Comment by FeodorFitsner** [comment]
We've just updated Ubuntu images with correct path to `octo` tool. It should be working now - please give it another try.

**Comment by olsh** [comment]
It works now, thank you! 👍🏻
