### ISSUE TITLE
GitLab merge requests

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#651]
Webhook MR requests has `X-Gitlab-Event: Merge Request Hook` header:
- Open MR: https://gist.github.com/FeodorFitsner/d01416e860944935d2ef#file-open-mr-json
- Update MR: https://gist.github.com/FeodorFitsner/d01416e860944935d2ef#file-update-mr-json
- Merge MR: https://gist.github.com/FeodorFitsner/d01416e860944935d2ef#file-merge-mr-json
- Close MR: https://gist.github.com/FeodorFitsner/d01416e860944935d2ef#file-close-mr-json

Fetching Merge Request on build worker:

```
git clone --branch={target_branch} https://gitlab.com/{target_repo}.git
git pull --no-ff https://gitlab.com/{source_repo}.git {source_branch}
```

> If MR is not "mergeable" second git command will fail.

Build status should be applied to `last_commit` SHA from MR webhook request and `target_repo` - GitLab creates virtual commit in the target repository.

**Comment by FeodorFitsner** [comment]
Requestor: https://gitlab.com/u/mrtux

**Comment by sigmavirus24** [comment]
It appears this is supported now? (https://gitlab.com/pycqa/flake8/merge_requests/94/builds)

**Comment by FeodorFitsner** [comment]
it's just AppVeyor setting commit statuses. No full-fledged MR support yet.

**Comment by Ede123** [comment]
Does this mean GitLab merge requests will currently not be handled by AppVeyor?

**Comment by mojavelinux** [comment]
I've configured GitLab to hit AppVeyor's webhook, but it's not causing a build to trigger. Is this integration not working yet?

**Comment by mcepl** [comment]
Works for me on [appveyor branch of M2Crypto](https://gitlab.com/mcepl/m2crypto/tree/appveyor). See [MR for this branch](https://gitlab.com/m2crypto/m2crypto/merge_requests/26).

**Comment by Ede123** [comment]
No, unfortunately there is still no support.

There are two cases which result in the MR status being updated, though (which was what confused me earlier, too, hence my last comment):
* First is @mcepl's case: Appveyor is enabled for `mcepl/m2crypto`, so the "personal" build result will be used to update the upstream MR status in `m2crypto/m2crypto`
* What also works is if all branches are in the same repo (i.e. if AppVeyor was enabled for `m2crypto/m2crypto` CI status would be updated for a MR from e.g. `m2crypto/m2crypto:new_feature` to `m2crypto/m2crypto:master` 

What does *not* work is the most common case for public projects:
* A contributor who has not enabled AppVeyor themselves wants to merge from their fork into the (AppVeyor enabled) upstream repository.<br/>AppVeyor knows nothing about the contributors fork (and therefore won't build) and the upstream request to AppVeyor is currently ignored (as MR's are still not supported).

**Comment by mojavelinux** [comment]
Thanks for this information @Ede123. You actually gave me an idea that I can use as a workaround. My company collects all patches for the upstream in branches of our fork. All we need to know is if those branches are good before merging. So we can just enable AppVeyor on our fork and we can at least get results for those changes. It's not ideal, but it's something.

**Comment by pfeigl** [comment]
Is there any work on this? What we would actullay want to accomplish is to only build `master` or branches which have merge requests.

When I disabled the push notifications and only enabled the MR notifications in Gitlab no builds were triggered anymore at all.

**Comment by IlyaFinkelshteyn** [comment]
Marked it for Q3 this year. Sorry it takes so long.

**Comment by sigmavirus24** [comment]
@IlyaFinkelshteyn some companies have different boundaries for their quarters. Would you be able to share the start/end-dates for Q3 for AppVeyor?

**Comment by IlyaFinkelshteyn** [comment]
@sigmavirus24 we use calendar year. This means that it should be done by the end of September, but I hope earlier.

**Comment by Ede123** [comment]
Exactly.

Yes, GitLab CI in merge requests shows the CI results of the fork / branch to be merged (it runs in the fork so-to say, which is a very nice feature on the one hand as CI just works for every fork without the forking users ever having to set up anything, but it also can cause issues as not all aspects of the fork and it's CI can be controlled)

**Comment by FeodorFitsner** [comment]
So, how do you think we should handle cases like this (private source repo from a different account)? Just skip the build if source repo unreadable?

**Comment by Ede123** [comment]
There's one thing I should've clarified: The soure repo is not public, but it's also not private, it's what GitLab calls "internal": everybody with an account has access.  (I guess creating a merge request from a really private repository into a public repository might not even be possible).  
In principle this would allow for the operation to succeed by using the already available credentials from the user who set up AppVeyor in the public target repository.

A pragmatic "fix" would do exactly what you mentioned: skip (or possibly even fail) the build if source repo is unreadable.

In either case it should not block the CI for "build_timeout * number of jobs" minutes (This is probably the only relevant detail).

**Comment by Ede123** [comment]
Another issue I found for GitLab merge requests:  
It seems the build status of merge requests is not properly updated for builds of the actual merge request (i.e. builds triggered by a merge request event).  
Only common branch builds (i.e. builds triggered by a push event as long as the source branch is in the same repository) result in an updated build status.

For an example see https://ci.appveyor.com/project/inkscape/inkscape/builds/19352413  
The build was successful but the build status of the MR was not updated (no indication this build was performed by AppVeyor whatsoever), see https://gitlab.com/inkscape/inkscape/merge_requests/357

**Comment by IlyaFinkelshteyn** [comment]
@Ede123 It seems that for GitLab we need to set status in the `head` repo in case MR is done from the fork. We will also probably write a warning in Events if user authorized by AppVeyor is forbidden from setting the status on that repo. Fix is on it's way, will update as deployed.

**Comment by IlyaFinkelshteyn** [comment]
@Ede123 build status issue is fixed.

**Comment by Ede123** [comment]
@IlyaFinkelshteyn: I've watched the build process for some days now, but I'm not seeing any change. The build status in MR's is still not properly updated.

Is the fix deployed yet? Or did I misunderstand how you attempted to fix it? The problematic case I'm looking at are merge requests where the source branch is from a fork. Builds are properly triggered and executed by AppVeyor, but the build status of the MR is still not updated.

Also unfixed is the timeout issue when the source branch is from a fork with limited visibility that can not be accessed by AppVeyor without providing credentials.

**Comment by IlyaFinkelshteyn** [comment]
@Ede123 yes it is deployed. Thank you for noticing this, it is a permission issue. You need to add a user AppVeyor authorized with as a member with `Developer` role. I updated [blog post](https://www.appveyor.com/blog/2018/11/06/gitlab-bitbucket-merge-pull-requests/), please check fork mr/pr related section.

Timeout issue is still on me and it is the reason this issue is still open,

**Comment by Ede123** [comment]
@IlyaFinkelshteyn but we *do* have AppVeyor authorized by a member with at least "Developer" rights (with owner rights actually) unless I'm missing something:

![image](https://user-images.githubusercontent.com/904570/48295990-d6352c80-e491-11e8-91c1-dc637f748a1e.png)

![image](https://user-images.githubusercontent.com/904570/48295998-01b81700-e492-11e8-9491-8554e46d8182.png)

**Comment by IlyaFinkelshteyn** [comment]
On the head/source repo? GitLab PR status should be set in the head/source repo...

**Comment by Ede123** [comment]
Ah, so the source branch of the MR (i.e. for an OpenSource project usually a "random" contributor)? We obviously don't have that permission I'm afraid.

So even if an MR is opened in the "upstream" repository (e.g. Inkscape proper) the MRs build status *needs* to be set in the fork? Is there any way around it?

If not it's obviously a very bad design decision of GitLab and I'd try to bring it up with them (if there isn't a report already)

**Comment by IlyaFinkelshteyn** [comment]
They have to be aware. I found number of discussions in their forums.

**Comment by sigmavirus24** [comment]
@Ede123 this is also a problem for Jenkins so they are aware and they just don't care because it works for GitLab CI
